### PR TITLE
Fix a rendering glitch in event loop mardown

### PR DESCRIPTION
**Pull request by mcollina**
Nested lists were not rendered as nested.

Fixes https://github.com/nearform/node-clinic/issues/34

### CODE REVIEW

**Comment by BridgeAR** [comment]
Does this also apply to e.g., gc-readmore.md? There are other files that are nesting the entries just like it was done here as well.

**Comment by mcollina** [comment]
@BridgeAR good catch!

**Comment by mcollina** [comment]
PTAL

**Comment by BridgeAR** [comment]
I did not test the actual view tough.

**Pull request merged**
