### PR TITLE
Implement common icons

### PR DESCRIPTION
**Pull request by iamstuartwilson**
This PR should go out after releasing a new version of common once [this PR](https://github.com/nearform/node-clinic-common/pull/10) is merged and bumping the dependency.

## Overview
Uses Clinic Common repo icons in place of those previously kept within this repo.

## Screenshot
image

### CODE REVIEW

**Comment by iamstuartwilson** [comment]
@AlanSl this one is now ready to review with the new release of Clinic Common in place 👍

**Comment by AlanSl** [comment]
There's a html `❮` and when opened `❯` that should be replaced with the appropriate icons:

image

And while you're at it, can you add up / down arrows to "Read more" / "Read less" at the bottom of that section there, similar to "Recommendations"?

Everything else looks good

**Comment by iamstuartwilson** [comment]
Cheers @AlanSl , will update this afternoon!

**Comment by iamstuartwilson** [comment]
@AlanSl I had to restructure the read more toggles using the D3 API as they were using pseudo content for the text, if you could check how that's been implemented it would be great.  Screenshot of implementation below:

doctor-chevrons

**Pull request merged**
